version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
    environment:
      - MONGO_URI=mongodb://mongo:27017/reading_app
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: